---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: learn
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: learn
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-app

